### ISSUE TITLE
Network route problem

### ISSUE THREAD

**Issue by wgfilho** [netbirdio/ios-client#11]
Hi!

I have a an intermittent problem on the iOS client. This is what I do:

- Network route is configured
- On iOS, connect to Netbird
- Try to ping any internal ip/name, it doesn't work
- Connect/disconnect a few times, eventually it works.
- Sometimes, I try on the iOS client to disable/reenable the network route and everything starts working.

It's weird because it's intermittent, sometimes I'm able to ping, sometimes not. So, I guess that means that the configuration is correct.

What information do you need me to provide to help debug it? This behavior does not happen on the other clients (Mac or Linux)

Thanks!

**Comment by pascal-fischer** [comment]
Hi @wgfilho,

I assume you are trying to reach a machine behind the network route?
Can you enable trace logs in the advanced settings and send logs from one of the not-working sessions? Also are you able to ping the netbird peer IP while the route is not working? Is the peer marked as successfully connected and has the route configured in the peers overview?

**Comment by wgfilho** [comment]
Hi! I tried a lot of times and it looks like the problem is not happening anymore. I updated the version of all the apps (iOS and Linux), but I don't know if this is was fixed the issue. In any case, thank you very much!

**Comment by pascal-fischer** [comment]
Good to hear that it works for you now. I will close the issue for now. If you are experiencing problems again just reopen it.
