### ISSUE TITLE
Keep refreshing in the background to ensure that Netbird is in a connected state.

### ISSUE THREAD

**Issue by jiangslee** [netbirdio/ios-client#9]
After my Netbird ios-client opened the connection, I switched to other apps. Not long after opening other apps, Netbird ios-client was in disconnected state.

It is hoped that the ios-client of Netbird will add the ability to keep refreshing in the background to ensure that Netbird ios-client is in a connected state.

iOS 17.4.1
netbird ios-client 0.0.3

**Comment by mlsmaycon** [comment]
Hello @jiangslee, this shouldn't be the case. To help us understand the case better, can you update the app to the latest version, enable trace logs, and export them by accessing the Advanced menu of NetBird's app?
